### ISSUE TITLE
Role -> Multiple role created with same name

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#1]
![Screenshot (152)](https://github.com/antonym8/Tentacle/assets/142376069/0b42fd61-5c1b-49b6-8625-7d398f3410d3)

**Comment by Gokilavani-m8** [comment]
While entering already existing role name, the toast message should appear as **Role Name Already Exists**. No toast message has displayed

**Comment by yogiofficemail** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Not fixed

**Comment by yogiofficemail** [comment]
frontend issue validation sent 
{
    "status": 400,
    "message": "The name has already been taken."
}
@M8Balaji

**Comment by M8Balaji** [comment]
Fixed

**Comment by Nounitha-m8** [comment]
Pass
