### ISSUE TITLE
Govt Id proof -> Spelling mistake

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#10]
Spelling should be "Govt"

![Screenshot (156)](https://github.com/antonym8/Tentacle/assets/142376069/7d2b01ca-e135-4843-8d83-0b3b3a6feda7)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 17-01-2024

**Comment by Gokilavani-m8** [comment]
Pass
