### ISSUE TITLE
Attendance -> Employee joining date

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#102]
Employee joining date was February but that employee name shows in January attendance list

[screen-capture (1).webm](https://github.com/antonym8/Tentacle/assets/142376069/c433c8de-fcf0-4e15-a2e7-3c91e55b7d33)

**Comment by M8Balaji** [comment]
@yogiofficemail  Check and close this issue - https://tssapidemo.m8itsolutions.in/api/employeeManualAttendanceList

**Comment by yogiofficemail** [comment]
fixed

**Comment by Gokilavani-m8** [comment]
Employee joining date was march but that employee name is not shown in attendance list

[Recording-20240707_230104.webm](https://github.com/antonym8/Tentacle/assets/167422482/08e02f00-4888-47d5-9346-593176b44d63)

**Comment by yogiofficemail** [comment]
fixed

**Comment by Gokilavani-m8** [comment]
Employee joining date was march but the employee name is displayed in both months (March & July). Need to fix it

[Recording-20240711_215439.webm](https://github.com/user-attachments/assets/a1e589fc-ea16-4d1a-b949-655b482dbb63)

**Comment by yogiofficemail** [comment]
yes if the employee is joined in march then after march 2015 all the month the attendance has to be given right 
if you select the date before march 2015 then it will not show 
according to flow it is correct right

**Comment by Gokilavani-m8** [comment]
Pass
