### ISSUE TITLE
Email & password placeholders

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#103]
"Slug name" shows in email and password placeholders

![Screenshot (408)](https://github.com/antonym8/Tentacle/assets/142376069/f9290d1a-f525-4b3d-9f73-d202d215fc5c)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed 09-04-2024

**Comment by Nounitha-m8** [comment]
Not Fixed

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Pass
