### ISSUE TITLE
User -> Added user not shows in the list

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#104]
[screen-capture (2).webm](https://github.com/antonym8/Tentacle/assets/142376069/ccbc2d63-ca32-4062-937d-61743d4f6872)

**Comment by muthuraja-m8itsolutions** [comment]
Not an issue - 09-04-2024

**Comment by Nounitha-m8** [comment]
User>Add new>Add Button is not working

**Comment by M8Balaji** [comment]
fixed

**Comment by Gokilavani-m8** [comment]
Pass
