### ISSUE TITLE
Add user success toast message

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#105]
Proper message should display

![Screenshot (409)](https://github.com/antonym8/Tentacle/assets/142376069/a749365a-19aa-4c09-82a9-4ac6e169c807)

**Comment by M8Balaji** [comment]
fixed

**Comment by Gokilavani-m8** [comment]
Proper message should display- Fixed
Created at - Need to show correct time

![Screenshot (96)](https://github.com/antonym8/Tentacle/assets/167422482/f2543bf8-668c-4826-be06-c7b5fdc01bc2)

**Comment by M8Balaji** [comment]
@yogiofficemail  Check and close the above issue 

https://tssapidemo.m8itsolutions.in/api/userAdd

**Comment by yogiofficemail** [comment]
creating time is automatic db will automatically update it it can be changed by add 5hr to the created date while showing

**Comment by Gokilavani-m8** [comment]
Pass
