### ISSUE TITLE
Client / Allowance -> Amount shows empty

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#108]
![Screenshot (411)](https://github.com/antonym8/Tentacle/assets/142376069/37782deb-1d27-466d-976c-221ebcbefc13)

**Comment by M8Balaji** [comment]
@yogiofficemail  Amount coming as null https://tssapidemo.m8itsolutions.in/api/clientCategoryList/37/7

**Comment by yogiofficemail** [comment]
need calrification in this flow 
https://tsswebdemo.m8itsolutions.in/masters/client/allowance there is no amount is saving in this form then how to calculate the amount the here

**Comment by yogiofficemail** [comment]
if the amount is saved directly then it will show  if not it will not show amount

**Comment by Gokilavani-m8** [comment]
where is the amount is saved?

**Comment by yogiofficemail** [comment]
there is no amount saving that is what i am asking

**Comment by Gokilavani-m8** [comment]
Pass
