### ISSUE TITLE
Client / Allowance -> In edit deductions fields are empty

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#109]
[screen-capture (4).webm](https://github.com/antonym8/Tentacle/assets/142376069/e14ab696-bf1d-41fd-b359-336f288f5509)

**Comment by M8Balaji** [comment]
https://tssapidemo.m8itsolutions.in/api/clientallowancedeductionsList/28 - Not Working, Some times giving null in the Data field
@yogiofficemail Check and let me know

**Comment by yogiofficemail** [comment]
fixed
[05.07.2024 21_34.webm](https://github.com/antonym8/Tentacle/assets/112150339/c1c20c37-813c-484e-b487-a476bfed6ad8)

**Comment by Gokilavani-m8** [comment]
Pass
