### ISSUE TITLE
Attendance -> Month working days

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#110]
Working days shows 31 in default but it should display based on the month

![Screenshot (412)](https://github.com/antonym8/Tentacle/assets/142376069/c70b2b14-3b52-45f0-ba69-a98086b71919)

**Comment by M8Balaji** [comment]
@yogiofficemail Check and fix it
https://tssapidemo.m8itsolutions.in/api/employeeManualAttendanceList/19?year=2024&month=06

**Comment by yogiofficemail** [comment]
fixed

**Comment by Gokilavani-m8** [comment]
Pass
