### ISSUE TITLE
Employee management -> payslip enable / disable confirm message

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#111]
When disable or enable it shows the same confirmation box and disable button

![Screenshot (413)](https://github.com/antonym8/Tentacle/assets/142376069/daa817f3-4c10-4efa-b4e5-e2195af5a794)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 03-04-2024

**Comment by Nounitha-m8** [comment]
Not Fixed

**Comment by M8Balaji** [comment]
Not an issue

**Comment by Nounitha-m8** [comment]
Pass
