### ISSUE TITLE
Payslip -> Location not displayed

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#112]
![Screenshot (414)](https://github.com/antonym8/Tentacle/assets/142376069/0606b7f2-94c1-4d7d-9393-5e5c062eee8e)

**Comment by muthuraja-m8itsolutions** [comment]
Not an issue. While creating employee's client we need to add clients details such as location. Not an issue

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Need to show the location 

![Screenshot (342)](https://github.com/antonym8/Tentacle/assets/167422482/af1273db-9344-4c2f-9313-8383d284ccb4)

**Comment by M8Balaji** [comment]
Fixed

**Comment by Nounitha-m8** [comment]
Pass
