### ISSUE TITLE
Due date

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#119]
Due date field shows todays date

![Screenshot_20240311_124650](https://github.com/antonym8/Tentacle/assets/142376069/e308b943-8a53-427f-94ed-88b7bf011902)

**Comment by M8Naveen** [comment]
Backend need to fix this issue

**Comment by M8Naveen** [comment]
validation fixed in front end. needed to clear the issue in backend also

**Comment by yogiofficemail** [comment]
fixed if the admin panel change the value it will reflect in the app

**Comment by Gokilavani-m8** [comment]
Pass
