### ISSUE TITLE
Govt Id proof -> Validation message (Common issue for all modules)

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#12]
Validation message should be removed after click on Reset button

[screen-capture (3).webm](https://github.com/antonym8/Tentacle/assets/142376069/53803eeb-09bf-4b28-a8c4-608686f84191)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 03-04-2024

**Comment by Gokilavani-m8** [comment]
Pass
