### ISSUE TITLE
Master>Finance>loan

### ISSUE THREAD

**Issue by Gokilavani-m8** [antonym8/Tentacle#120]
While clicking on delete icon, it can't be deleted

![Screenshot (4)](https://github.com/antonym8/Tentacle/assets/167422482/8212c120-7295-466a-aa43-377ba2817971)

**Comment by M8Balaji** [comment]
@yogiofficemail 
![image](https://github.com/antonym8/Tentacle/assets/150112780/9f1bbfc1-972e-4189-b7dd-f1a5cdbecc3e)
https://tssapidemo.m8itsolutions.in/api/deleteFinaceCategories/169 Check and close this issure

**Comment by yogiofficemail** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Pass
