### ISSUE TITLE
Master>Finance>Bonus

### ISSUE THREAD

**Issue by Gokilavani-m8** [antonym8/Tentacle#121]
While clicking on the delete icon, it can't be deleted
![Screenshot (5)](https://github.com/antonym8/Tentacle/assets/167422482/5b3212a8-2ea2-4c53-a82b-285677bd725b)

**Comment by M8Balaji** [comment]
@yogiofficemail https://tssapidemo.m8itsolutions.in/api/deleteFinaceCategories/167
![image](https://github.com/antonym8/Tentacle/assets/150112780/5bc09372-d220-4486-9a8d-827c1555409c)
Check and close this issue

**Comment by yogiofficemail** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
While entering the bonus name and clicking on the add new icon, bonus name not added

[Video0.webm](https://github.com/antonym8/Tentacle/assets/167422482/41709d62-dd7f-42c8-80ae-e88601e8bf3f)

**Comment by yogiofficemail** [comment]
[05.07.2024 20_51.webm](https://github.com/antonym8/Tentacle/assets/112150339/a6fa8a3d-9f54-4eb7-ba33-5ebd8da6bc5c)
working

**Comment by Gokilavani-m8** [comment]
Pass
