### ISSUE TITLE
Master>Branch>Bio Metrics

### ISSUE THREAD

**Issue by Gokilavani-m8** [antonym8/Tentacle#123]
Message should be displayed as "Confirm to Delete Biometrics ?" not "floor"

![Screenshot (9)](https://github.com/antonym8/Tentacle/assets/167422482/3399416e-62d3-41c3-b159-a67e9f86a0c7)

**Comment by M8Balaji** [comment]
fixed

**Comment by Nounitha-m8** [comment]
Spelling in a present word Confirm to delete biometric - Need to change the **Confirm to Delete Biometrics ?**

<img width="818" alt="Capture20" src="https://github.com/antonym8/Tentacle/assets/167423207/9a5b6f00-1916-43a3-b306-0881922f2aea">

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Pass
