### ISSUE TITLE
Master>Client>Allowances

### ISSUE THREAD

**Issue by Gokilavani-m8** [antonym8/Tentacle#124]
After deleting the allowance name, the toast message should be displayed as **Allowances Deleted Successfully** not "Deleted Successfully"

![Screenshot (10)](https://github.com/antonym8/Tentacle/assets/167422482/d7f53c0e-62a8-4b2a-a117-b30c9ae1156e)

**Comment by yogiofficemail** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Not fixed

**Comment by yogiofficemail** [comment]
fixed

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Pass
