### ISSUE TITLE
Master>Client>Deductions

### ISSUE THREAD

**Issue by Gokilavani-m8** [antonym8/Tentacle#125]
After deleting the deductions, the toast message should be displayed as **Deductions Deleted Successfully** not "Deleted Successfully"

![Screenshot (11)](https://github.com/antonym8/Tentacle/assets/167422482/26077903-a32f-46ed-9970-d5ff3c49e813)

**Comment by Gokilavani-m8** [comment]
Rename the highlighted portion as **Deduction Name**

![Screenshot (216)](https://github.com/antonym8/Tentacle/assets/167422482/a2052332-5822-4704-bd7a-49dbd757ac38)

**Comment by yogiofficemail** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Not fixed

**Comment by yogiofficemail** [comment]
fixed

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Pass
