### ISSUE TITLE
Master>Employee>User

### ISSUE THREAD

**Issue by Gokilavani-m8** [antonym8/Tentacle#126]
1. After adding a new user and clicking on the add icon, a toast message should be displayed. But no toast message is displayed. It should be displayed as **Employee Name Added Successfully**
2. Employee Name should be displayed. It shouldn't be empty

![Screenshot (12)](https://github.com/antonym8/Tentacle/assets/167422482/55c76d26-b4ef-45fd-aecd-578a41f49d9e)

**Comment by M8Balaji** [comment]
fixed

**Comment by Nounitha-m8** [comment]
Pass
