### ISSUE TITLE
Govt Id proof -> New proof not created

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#13]
Created successfully message displayed but proof not displayed in the list

[screen-capture (4).webm](https://github.com/antonym8/Tentacle/assets/142376069/f1b108f8-1ce7-4125-9c80-aecc27c61c32)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 03-04-2024

**Comment by Gokilavani-m8** [comment]
Pass
