### ISSUE TITLE
Masters>Client>Add new

### ISSUE THREAD

**Issue by Gokilavani-m8** [antonym8/Tentacle#132]
1. Client Name - It shouldn't accept numbers & special characters as input. It shouldn't accept only the spaces as inputs. Spaces between the words should be acceptable.
2. Contact Person Name - It shouldn't accept numbers & special characters as input. It shouldn't accept only the spaces as inputs. Spaces between the words should be acceptable.
3. Need to remove the highlighted portion in mobile number

![Screenshot (247)](https://github.com/antonym8/Tentacle/assets/167422482/4faba244-7f8e-4342-9a71-da452c5f8b90)

4. Rename the Popup message as **Confirm to Delete Client...?**

![Screenshot (248)](https://github.com/antonym8/Tentacle/assets/167422482/b7ce6a03-a414-4e46-a034-10dbb209601e)

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Pass
