### ISSUE TITLE
Master>Client>Deductions 

### ISSUE THREAD

**Issue by Gokilavani-m8** [antonym8/Tentacle#134]
Rename the highlighted portion as Deduction Name

![image](https://github.com/antonym8/Tentacle/assets/167422482/824a2f08-83d6-4deb-a43e-b5f95f79ff59)

**Comment by M8Balaji** [comment]
Fixed

**Comment by yogiofficemail** [comment]
close this

**Comment by Gokilavani-m8** [comment]
Pass
