### ISSUE TITLE
Masters>Client>Add new

### ISSUE THREAD

**Issue by Gokilavani-m8** [antonym8/Tentacle#135]
1. Client Name - Rename the alert message as **Please Enter a valid "Client name"**

![Screenshot (346)](https://github.com/antonym8/Tentacle/assets/167422482/bf6b4494-308d-4644-8ebd-e642bb7f52bc)

2. Location - It shouldn't accept numbers & special characters as input. It shouldn't accept only the spaces as inputs. Spaces between the words should be acceptable.
3. Address - It shouldn't accept spaces as input. Spaces between the words should be acceptable.
4. Rename the title as **Client Name**

![Screenshot (347)](https://github.com/antonym8/Tentacle/assets/167422482/c3db7426-e211-44fc-a8a3-729cb9fddcc0)

5. Location - While entering the spaces as input, a proper alert message should be shown on the page. Rename the alert message as **Please Enter a valid "Location"**

![Screenshot (348)](https://github.com/antonym8/Tentacle/assets/167422482/6063dcdd-de8c-4593-b530-ebe73cf130d9)

**Comment by M8Balaji** [comment]
Fixed

**Comment by Nounitha-m8** [comment]
Pass
