### ISSUE TITLE
Department -> Entered slug name not showing in the list

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#14]
Created new department with slug name but in list page slug name column is empty

[screen-capture (5).webm](https://github.com/antonym8/Tentacle/assets/142376069/e001f52d-d590-4082-8866-01524c80a4e4)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 17-01-2024

**Comment by Gokilavani-m8** [comment]
Pass
