### ISSUE TITLE
Department -> Cancel button is not working in edit

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#15]
![Screenshot (157)](https://github.com/antonym8/Tentacle/assets/142376069/ee30e923-32b7-4fe4-b67d-9df58cbdb3e7)

**Comment by M8Balaji** [comment]
@Gokilavani-m8 @Nounitha-m8 Fixed in Local

**Comment by Gokilavani-m8** [comment]
@M8Balaji  After editing the department, cancel and save button is not working.
While editing a department and clicking on the save button, the department is not visible in the view list page.

**Comment by Gokilavani-m8** [comment]
1. After adding new department, the toast message should appear as **Department Added Successfully**. Need to remove list in toast message

![Screenshot (212)](https://github.com/antonym8/Tentacle/assets/167422482/7e373bba-a426-4e88-bea5-8e0b97dcc8b6)

2. Rename the alert message as **Please enter "Department Name"**

![Screenshot (213)](https://github.com/antonym8/Tentacle/assets/167422482/03077c4c-8d2c-481d-a258-afbe7261b148)

**Comment by yogiofficemail** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Not fixed

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Pass
