### ISSUE TITLE
Department -> Description field in edit

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#16]
Description field is not mandatory field in create but in edit page description field is showing as mandatory field

![Screenshot (158)](https://github.com/antonym8/Tentacle/assets/142376069/3b2d49aa-c093-453b-9bb1-7f33a1ef5fe6)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 03-04-2024

**Comment by Gokilavani-m8** [comment]
Pass
