### ISSUE TITLE
Department -> Save button not working in edit

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#17]
[screen-capture (6).webm](https://github.com/antonym8/Tentacle/assets/142376069/a196d044-1780-4c90-93e7-65211de2f096)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 03-04-2024

**Comment by Gokilavani-m8** [comment]
Save button is not working - Not fixed

**Comment by M8Balaji** [comment]
Fixed - Working fine

**Comment by Gokilavani-m8** [comment]
Pass
