### ISSUE TITLE
Designation -> Spelling mistake

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#18]
![Screenshot (159)](https://github.com/antonym8/Tentacle/assets/142376069/d564f178-4d01-4ac3-bd53-b3189b9e8253)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 03-04-2024

**Comment by M8Balaji** [comment]
@Gokilavani-m8 
There is no **Designation** Module currently, So please close the issue

**Comment by Gokilavani-m8** [comment]
Pass
