### ISSUE TITLE
Designation -> validation message

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#19]
Proper validation message should display

![Screenshot (160)](https://github.com/antonym8/Tentacle/assets/142376069/2a206335-61b7-4f82-89e1-7a549a3f5783)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 03-04-2024 (UI changed based on the client changes)

**Comment by M8Balaji** [comment]
@Gokilavani-m8  Please close the issue, Currently Designation module is Removed

**Comment by Gokilavani-m8** [comment]
Pass
