### ISSUE TITLE
Designation -> Description field in edit

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#21]
In add page description field is not mandatory but in edit page it's mandatory

![Screenshot (162)](https://github.com/antonym8/Tentacle/assets/142376069/c91786ae-9bd0-458a-a313-d1e5b3c14f86)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 03-04-2024 (UI changed based on client changes)

**Comment by M8Balaji** [comment]
@Gokilavani-m8 
 Please close the issue, Currently Designation module is Removed

**Comment by Gokilavani-m8** [comment]
Pass
