### ISSUE TITLE
Break -> Add break validation message

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#22]
Proper validation message should display

![Screenshot (163)](https://github.com/antonym8/Tentacle/assets/142376069/27bc9dff-1ee7-48ab-b222-fa5cd43e2eba)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 03-04-2024

**Comment by Nounitha-m8** [comment]
Not Fixed

**Comment by M8Balaji** [comment]
Fixed

**Comment by Nounitha-m8** [comment]
Pass
