### ISSUE TITLE
Caste -> Delete confirmation message

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#26]
It's showing "Caster" but it should be "Caste"

![Screenshot (165)](https://github.com/antonym8/Tentacle/assets/142376069/3d6e7b79-e3ad-4dc3-bfd1-b74ae5bbc24a)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed 10-04-2024

**Comment by Nounitha-m8** [comment]
Not Fixed

**Comment by M8Balaji** [comment]
Fixed

**Comment by Nounitha-m8** [comment]
Pass
