### ISSUE TITLE
Blood group -> Create with + and -

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#27]
Not able to create blood group with + and - symbols

![Screenshot (166)](https://github.com/antonym8/Tentacle/assets/142376069/96794c86-f329-409f-b4e0-b1bb14c7b422)

**Comment by muthuraja-m8itsolutions** [comment]
It will accept only blood groups, It will not accept other names

**Comment by Nounitha-m8** [comment]
Pass
