### ISSUE TITLE
Role -> Edit role with blank description field

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#3]
Deleted description and updated the role. Role updated successfully message displayed but description not deleted.

[screen-capture.webm](https://github.com/antonym8/Tentacle/assets/142376069/a5d6c41a-8644-4a25-a523-7cfcb08c4693)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 04-04-2024

**Comment by Gokilavani-m8** [comment]
Pass
