### ISSUE TITLE
Consultancy agent -> Edit not working

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#32]
[screen-capture (12).webm](https://github.com/antonym8/Tentacle/assets/142376069/b72e78e7-72ca-4d38-af46-159cffbe12e0)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed 10-04-2024

**Comment by Nounitha-m8** [comment]
Not Fixed

**Comment by M8Balaji** [comment]
Fixed

**Comment by Nounitha-m8** [comment]
**Consultancy agent>Add new>Contact Person name** - It shouldn't accept numbers & special characters (except dot, space, hyphen & slash) as input. It shouldn't accept only the spaces as inputs. Spaces between the words should be acceptable
**Consultancy agent>Add new>Phone** - It shouldn't accept spaces, alphabets, special characters & numbers less than or more than 10 digits as inputs

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Pass
