### ISSUE TITLE
Security agent -> Edit page save button disabled after error message

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#35]
![Screenshot (171)](https://github.com/antonym8/Tentacle/assets/142376069/28f54965-36d7-43af-9e51-043c37eb0860)

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Security agent -> Edit page save button disabled after error message - Pass
After adding a new security agent, a toast message should appear as **Security Agents Added Successfully**
After editing a new security agent, a popup message should appear as **Security Agents Updated Successfully**

**Comment by M8Balaji** [comment]
@yogiofficemail  2, 3 point fix it
https://tssapidemo.m8itsolutions.in/api/addAgents

https://tssapidemo.m8itsolutions.in/api/updateAgents

**Comment by yogiofficemail** [comment]
fixed

**Comment by Gokilavani-m8** [comment]
Pass
