### ISSUE TITLE
Employment type -> Spelling mistake

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#36]
![Screenshot (172)](https://github.com/antonym8/Tentacle/assets/142376069/c471a1ed-bb36-4cd1-9acd-efb5bb47ebe2)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed -04-04-2024

**Comment by Nounitha-m8** [comment]
Not Fixed

**Comment by Nounitha-m8** [comment]
Pass
