### ISSUE TITLE
Employment type -> Spelling mistake in toast message

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#38]
![Screenshot (173)](https://github.com/antonym8/Tentacle/assets/142376069/97ed1961-b9a7-455d-bc9c-0161c8c07967)

**Comment by M8Balaji** [comment]
@yogiofficemail  Check this API and correct this issue
https://tssapidemo.m8itsolutions.in/api/addEmployeetype

**Comment by yogiofficemail** [comment]
Fixed

**Comment by Nounitha-m8** [comment]
Pass
