### ISSUE TITLE
Employment type -> Validation message in edit

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#39]
Tag name is not mandatory in add but it showing error in edit
Validation message should "Tag name must be string" not "description"

![Screenshot (174)](https://github.com/antonym8/Tentacle/assets/142376069/fe3ea60a-c4a4-42bf-94ab-593f065c0c0f)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 04-04-2024

**Comment by Nounitha-m8** [comment]
Tag name proper validation message should display

**Comment by M8Balaji** [comment]
Fixed

**Comment by Nounitha-m8** [comment]
Need to represent the tag name as mandatory field with an asterisk symbol

**Comment by M8Balaji** [comment]
Fixed

**Comment by Nounitha-m8** [comment]
1.Rename the field name as **Staff name**  not as staffing name - Need to correct it.
2.Need to change the placeholder as Enter staff name.

![Screenshot (283)](https://github.com/antonym8/Tentacle/assets/167423207/f48828be-79e3-4076-a5ee-616f38088bab)

3.Wrong time shown in created at employment type in employment type list page - Need to correct it.
![Screenshot (284)](https://github.com/antonym8/Tentacle/assets/167423207/2661ee95-0e7e-4913-a833-a9c6066b5f16)

**Comment by Gokilavani-m8** [comment]
Pass
