### ISSUE TITLE
Role -> Confirm delete alert message

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#4]
Message should display "Confirm to delete role" not "user"

![Screenshot (153)](https://github.com/antonym8/Tentacle/assets/142376069/790f5aeb-020a-4361-9f5c-42775fefdb69)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 17-01-2024

**Comment by Gokilavani-m8** [comment]
Pass
