### ISSUE TITLE
Employment type -> Edit not working

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#40]
Updated successfully message displayed but data not saved

Spelling also mistake in toast message

[screen-capture (14).webm](https://github.com/antonym8/Tentacle/assets/142376069/9ee9b154-6bb8-457a-b60b-b9ab4dca5aa4)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 04-04-2024

**Comment by Nounitha-m8** [comment]
Spelling mistake in **employeetype updated successfully** need to change **Employment Type Updated Successfully**

**Comment by M8Balaji** [comment]
@yogiofficemail Check this API and Fix the issue

https://tssapidemo.m8itsolutions.in/api/updateEmployeetype

**Comment by yogiofficemail** [comment]
fixed

**Comment by Nounitha-m8** [comment]
@M8Balaji  After editing the edit employment type, a blank toast message has displayed

![Screenshot (165)](https://github.com/antonym8/Tentacle/assets/167423207/7b781df2-7a30-4a8c-9b3e-1213654e9d44)

**Comment by yogiofficemail** [comment]
> @M8Balaji After editing the edit employment type, a blank toast message has displayed
> 
> ![Screenshot (165)](https://private-user-images.githubusercontent.com/167423207/335460430-7b781df2-7a30-4a8c-9b3e-1213654e9d44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMzUzNTksIm5iZiI6MTcxNzEzNTA1OSwicGF0aCI6Ii8xNjc0MjMyMDcvMzM1NDYwNDMwLTdiNzgxZGYyLTdhMzAtNGE4Yy05YjNlLTEyMTM2NTRlOWQ0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQwNTU3MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MzcwYzRkODIxZGYyYTQyOTJkNTJiODM3NzZlZGJkZjBkODZmNWNlNjE0YjJkMGIzNzQ4MDMzZGIzNzk2NzczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.K_NN_Cov_hF1DD-uO3C1kBoZwyx0iqnVqzRUUaaT5YQ)

fixed

**Comment by Nounitha-m8** [comment]
@M8Balaji  @yogiofficemail  Spelling mistake in employeetype updated successfully need to change Employment Type Updated Successfully 
![Screenshot (166)](https://github.com/antonym8/Tentacle/assets/167423207/7056f18a-9e66-4da0-ba72-453738b4e3ab)

**Comment by yogiofficemail** [comment]
> @M8Balaji @yogiofficemail Spelling mistake in employeetype updated successfully need to change Employment Type Updated Successfully ![Screenshot (166)](https://private-user-images.githubusercontent.com/167423207/335463287-7056f18a-9e66-4da0-ba72-453738b4e3ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMzYxNzQsIm5iZiI6MTcxNzEzNTg3NCwicGF0aCI6Ii8xNjc0MjMyMDcvMzM1NDYzMjg3LTcwNTZmMThhLTllNjYtNGRhMC1iYTcyLTQ1MzczOGI0ZTNhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQwNjExMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjM5NzdkYmQxMjg2OGRlMDJiZmQxNWQ2YjY5ZmM3ZDYwZjk2YjRmZDBmNzVkNTQyYWU5ZDdjMDkxOGE3MDg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.B6u19S8dQ1wnp1hxvbbcgJag0OCrsdDB4_bgCBHGTxc)

changed

**Comment by Nounitha-m8** [comment]
Pass
