### ISSUE TITLE
Biometrics -> Multiple biometrics added with same name

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#43]
![Screenshot (177)](https://github.com/antonym8/Tentacle/assets/142376069/c13bddd7-c2a6-4c4a-bfb8-86ad442e20b6)

**Comment by M8Balaji** [comment]
@yogiofficemail https://tssapidemo.m8itsolutions.in/api/addBiometrics Check this Api and Fix it

**Comment by yogiofficemail** [comment]
fixed 

> @yogiofficemail https://tssapidemo.m8itsolutions.in/api/addBiometrics Check this Api and Fix it

fixed need to work in ui @M8Balaji

**Comment by Nounitha-m8** [comment]
Pass
