### ISSUE TITLE
Floor -> Create floor with existing name

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#46]
Add new button disabled after create new floor with existing name and no validation message displayed
![Screenshot (179)](https://github.com/antonym8/Tentacle/assets/142376069/23d3232d-485e-4528-a7c2-1543a6974a02)

**Comment by M8Balaji** [comment]
Fixed

**Comment by Nounitha-m8** [comment]
Not Fixed

**Comment by M8Balaji** [comment]
@yogiofficemail  
https://tssapidemo.m8itsolutions.in/api/addFloors - Check and close it

**Comment by yogiofficemail** [comment]
validation message is sent check response need to work in frontend

> @yogiofficemail https://tssapidemo.m8itsolutions.in/api/addFloors - Check and close it

**Comment by M8Balaji** [comment]
Message format is wrong - {
    "name": [
        "The name has already been taken."
    ]
}

Need a message as string @yogiofficemail

**Comment by yogiofficemail** [comment]
> Message format is wrong - { "name": [ "The name has already been taken." ] }
> 
> Need a message as string @yogiofficemail

{
    "status": 400,
    "message": "The name has already been taken."
}
change like this but still not fixed @M8Balaji

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Pass
