### ISSUE TITLE
Loan -> Description in edit

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#50]
Description is not mandatory in add but it showing mandatory in edit

![Screenshot (183)](https://github.com/antonym8/Tentacle/assets/142376069/b650df6a-851a-47db-88b4-bc053ed824d7)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 04-04-2024

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Loan -> Description in edit - Pass
After creating a new loan, a toast message has displayed but the created loan is not shown. Need to change it.

**Comment by M8Balaji** [comment]
@yogi
check and Change it 
https://tssapidemo.m8itsolutions.in/api/updateCategories

**Comment by yogiofficemail** [comment]
> Loan -> Description in edit - Pass After creating a new loan, a toast message has displayed but the created loan is not shown. Need to change it.

fixed

**Comment by yogiofficemail** [comment]
> @yogi check and Change it https://tssapidemo.m8itsolutions.in/api/updateCategories

fixed

**Comment by Nounitha-m8** [comment]
@yogiofficemail  @M8Balaji  
1.Need to change the appropriate toast message should be displayed. Finance Categories Added Successfully, need to change it to **Loan Added Successfully**, as well as in edit Finance Categories Updated Successfully, need to change it to **Loan Updated Successfully**

![Screenshot (175)](https://github.com/antonym8/Tentacle/assets/167423207/461a8cb1-875b-411c-9e8a-1d3c57b24dfb)

2.While creating a new loan with an already existing loan, a toast message should appear as loan already exists.

**Comment by M8Balaji** [comment]
@yogiofficemail Check and close above issues
https://tssapidemo.m8itsolutions.in/api/updateCategories
https://tssapidemo.m8itsolutions.in/api/updateCategories

**Comment by yogiofficemail** [comment]
fixed

**Comment by Nounitha-m8** [comment]
Pass
