### ISSUE TITLE
Loan -> Not able to delete loan

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#51]
![Screenshot (184)](https://github.com/antonym8/Tentacle/assets/142376069/951d8491-d147-457d-8675-786fbb48826b)

**Comment by M8Balaji** [comment]
@yogiofficemail 
![image](https://github.com/antonym8/Tentacle/assets/150112780/9addae58-d897-4a8e-98f8-19a71e369884)

https://tssapidemo.m8itsolutions.in/api/deleteFinaceCategories/126 Check and Fix it

**Comment by yogiofficemail** [comment]
> @yogiofficemail ![image](https://private-user-images.githubusercontent.com/150112780/335447924-9addae58-d897-4a8e-98f8-19a71e369884.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMzE1MjIsIm5iZiI6MTcxNzEzMTIyMiwicGF0aCI6Ii8xNTAxMTI3ODAvMzM1NDQ3OTI0LTlhZGRhZTU4LWQ4OTctNGE4ZS05OGY4LTE5YTcxZTM2OTg4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQwNDUzNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNzIyYWRkOTU1ZTY1Y2JmYjNiNGQwMDIyZjIwNTVjNGY3NDA2ZGQ0MTk5MTYwMjQ2NGE3ZDI2NzVmMDFhZTllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XKV81la41ahnHIhodIGXgQ3pKyizP8uuyfoaI87vjRs)
> 
> https://tssapidemo.m8itsolutions.in/api/deleteFinaceCategories/126 Check and Fix it

url is wrong here correct url is https://tssapidemo.m8itsolutions.in/api/deleteFinanceCategories/126

**Comment by Nounitha-m8** [comment]
@yogiofficemail  @M8Balaji  - Not Fixed 

![Screenshot (173)](https://github.com/antonym8/Tentacle/assets/167423207/0fae754b-42fb-4fc9-b52c-2a9ce2df12bb)

**Comment by yogiofficemail** [comment]
Need to work in frontend .
api is done

**Comment by M8Balaji** [comment]
@yogiofficemail Please re check
https://tssapidemo.m8itsolutions.in/api/deleteFinaceCategories/156
![image](https://github.com/antonym8/Tentacle/assets/150112780/8a2ede15-35fc-43c2-8b5d-5bbfde11aecb)

**Comment by yogiofficemail** [comment]
fixed

**Comment by Nounitha-m8** [comment]
Pass
