### ISSUE TITLE
Bonus -> Multiple data with same name

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#54]
Multiple bonus created with same name

![Screenshot (187)](https://github.com/antonym8/Tentacle/assets/142376069/a46dcec2-74ae-4791-9a9b-b622621ec5e0)

**Comment by M8Balaji** [comment]
@yogiofficemail Check and fix it
https://tssapidemo.m8itsolutions.in/api/addFinanceCategory

**Comment by yogiofficemail** [comment]
> @yogiofficemail Check and fix it https://tssapidemo.m8itsolutions.in/api/addFinanceCategory

duplicate issue fixed need to work in frontend @M8Balaji

**Comment by Nounitha-m8** [comment]
Pass
