### ISSUE TITLE
Expenses -> Description in edit

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#55]
![Screenshot (188)](https://github.com/antonym8/Tentacle/assets/142376069/b51080b6-486b-498b-b533-28ce7cd067b6)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 04-04-2024

**Comment by M8Balaji** [comment]
Fixed @Gokilavani-m8 @Nounitha-m8

**Comment by Nounitha-m8** [comment]
@M8Balaji  @yogiofficemail  
Need to change the appropriate toast message should be displayed. Finance Categories Added Successfully, need to change it to **Expenses Added Successfully** as well as in edit Finance Categories Updated Successfully, need to change it to **Expenses Updated Successfully**

![Screenshot (170)](https://github.com/antonym8/Tentacle/assets/167423207/d61076b1-c84b-42c0-a226-b408d0fcd404)

**Comment by M8Balaji** [comment]
@yogiofficemail  - Check and fix it 
https://tssapidemo.m8itsolutions.in/api/addFinanceCategory
https://tssapidemo.m8itsolutions.in/api/updateCategories

**Comment by yogiofficemail** [comment]
fixed

**Comment by Gokilavani-m8** [comment]
After adding and updating a new expenses name, the proper toast message has displayed. For the second time while adding and updating a new expenses name, the incorrect toast message has displayed and the added expenses name is not shown in the list page. Need to correct it

[Recording-20240630_231954.webm](https://github.com/antonym8/Tentacle/assets/167422482/8085264d-cc85-450f-9c08-18248c07af1e)

**Comment by M8Balaji** [comment]
@yogiofficemail  https://tssapidemo.m8itsolutions.in/api/addFinanceCategory check and close it

**Comment by yogiofficemail** [comment]
{
    "status": 400,
    "message": "The name has already been taken."
}


the response is sent like this but still no alert plz check @M8Balaji

**Comment by yogiofficemail** [comment]
first time the type value is sent through the api but after few try type value is not sent through the api 
https://tssapidemo.m8itsolutions.in/api/addFinanceCategory

@M8Balaji

**Comment by M8Balaji** [comment]
Fixed

**Comment by Nounitha-m8** [comment]
Pass
