### ISSUE TITLE
Expenses -> Multiple data added with same name

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#56]
![Screenshot (189)](https://github.com/antonym8/Tentacle/assets/142376069/a54b268c-5e31-43c4-90ec-68fd2bcd7324)

**Comment by M8Balaji** [comment]
@yogiofficemail https://tssapidemo.m8itsolutions.in/api/addFinanceCategory Check this and close 
Data were not adding again but it shows as Added Successfully

**Comment by yogiofficemail** [comment]
> @yogiofficemail https://tssapidemo.m8itsolutions.in/api/addFinanceCategory Check this and close Data were not adding again but it shows as Added Successfully

fixed only unique name will be allowed to added

**Comment by Nounitha-m8** [comment]
Multiple data added with same, a blank toast message has appeared 

![Screenshot (181)](https://github.com/antonym8/Tentacle/assets/167423207/efe9705f-f4f1-47cf-94f2-125162999d1b)

**Comment by M8Balaji** [comment]
@yogiofficemail  https://tssapidemo.m8itsolutions.in/api/addFinanceCategory

**Comment by yogiofficemail** [comment]
validation message is sent from the backend need to work in the frontend

**Comment by M8Balaji** [comment]
@yogiofficemail Message needed as string
{
  "name": [
    "The name has already been taken."
  ]
}

**Comment by M8Balaji** [comment]
{
  "name": [
    "The name has already been taken."
  ]
}  needed as string @yogiofficemail

**Comment by yogiofficemail** [comment]
sent as string but not shown

**Comment by Gokilavani-m8** [comment]
While adding new expenses, a blank message has displayed

![Screenshot (392)](https://github.com/antonym8/Tentacle/assets/167422482/695bd405-e60f-45e5-99ad-a093b97ab16f)

**Comment by yogiofficemail** [comment]
@M8Balaji frontend

**Comment by M8Balaji** [comment]
fixed

**Comment by Gokilavani-m8** [comment]
Pass
