### ISSUE TITLE
Fine -> Description in edit

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#57]
![Screenshot (190)](https://github.com/antonym8/Tentacle/assets/142376069/2f826f8f-c3a0-4ecf-8bac-7d4a3ae51cb6)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 04-04-2024

**Comment by M8Balaji** [comment]
Fixed

**Comment by Nounitha-m8** [comment]
Edit option is not available

![Screenshot (192)](https://github.com/antonym8/Tentacle/assets/167423207/a694c669-d979-4fed-86e0-ef8c543296b3)

**Comment by M8Balaji** [comment]
Fixed

**Comment by Nounitha-m8** [comment]
While clicking on three dot icon there is only edit option is shown, need to include **Delete** & **Show** option.

![Screenshot (287)](https://github.com/antonym8/Tentacle/assets/167423207/701d7b73-debd-40fb-ad15-e48a00d9bad4)

**Comment by Gokilavani-m8** [comment]
Pass
