### ISSUE TITLE
Fine -> Duplicate data added with same name

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#58]
![Screenshot (191)](https://github.com/antonym8/Tentacle/assets/142376069/6ec6578f-ac59-4b8c-92a2-70d5fd2f31d5)

**Comment by M8Balaji** [comment]
@yogiofficemail https://tssapidemo.m8itsolutions.in/api/addFinanceCategory Check and close this

**Comment by yogiofficemail** [comment]
> @yogiofficemail https://tssapidemo.m8itsolutions.in/api/addFinanceCategory Check and close this

fixed need to work in ui @M8Balaji

**Comment by Nounitha-m8** [comment]
Pass
