### ISSUE TITLE
Payment -> Duplicate data added with same name

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#60]
![Screenshot (193)](https://github.com/antonym8/Tentacle/assets/142376069/2031954f-29fa-4638-8032-0039fe357fdb)

**Comment by M8Balaji** [comment]
@yogiofficemail check and close this 
https://tssapidemo.m8itsolutions.in/api/addFinanceCategory

**Comment by yogiofficemail** [comment]
> @yogiofficemail check and close this https://tssapidemo.m8itsolutions.in/api/addFinanceCategory

fixed need to work in ui @M8Balaji

**Comment by Nounitha-m8** [comment]
Pass
