### ISSUE TITLE
Seasonal salary -> From date

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#61]
Selected current date but it's showing error

![Screenshot (194)](https://github.com/antonym8/Tentacle/assets/142376069/89fe4684-db6f-48a0-8a0f-4f3843865c96)

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
From date - While entering today's date in from date, the alert message has been displayed. It should accept today's date. Need to change it.

**Comment by Gokilavani-m8** [comment]
Pass
