### ISSUE TITLE
Seasonal salary -> Employee type dropdown is blank in edit

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#63]
Selected employee type in add but in edit it's not showing selected employee type

![Screenshot (196)](https://github.com/antonym8/Tentacle/assets/142376069/c0fcdba3-0d83-4ef4-bf03-a3c3126624a9)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 04-04-2024

**Comment by M8Balaji** [comment]
Fixed

**Comment by Nounitha-m8** [comment]
Pass
