### ISSUE TITLE
Seasonal salary -> Employee type showing the ID

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#65]
![Screenshot (198)](https://github.com/antonym8/Tentacle/assets/142376069/09942d6d-32cc-4a22-8f92-0f31a59f4733)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 04-04-2024

**Comment by M8Balaji** [comment]
fixed

**Comment by Nounitha-m8** [comment]
Pass
