### ISSUE TITLE
Holiday Scheme -> No of days placeholder and error message

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#66]
1. No of days placeholder showing the wrong name
2. Proper error message should display

![Screenshot (200)](https://github.com/antonym8/Tentacle/assets/142376069/2b22eb4e-92d9-4b7d-bc87-34a01f7ec801)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 04-04-2024

**Comment by Gokilavani-m8** [comment]
Not fixed

**Comment by M8Balaji** [comment]
Fixed

**Comment by Nounitha-m8** [comment]
No. Of Days & Grace Days - Does not show negative values

<img width="913" alt="Capture14" src="https://github.com/antonym8/Tentacle/assets/167423207/42c9cb09-fe9f-432e-8615-cca78ab78380">

**Comment by M8Balaji** [comment]
fixed

**Comment by Nounitha-m8** [comment]
Calculating Working days - Does not show negative values

![Screenshot (288)](https://github.com/antonym8/Tentacle/assets/167423207/18c312e9-d7cb-460d-b565-103346894c4d)

**Comment by Gokilavani-m8** [comment]
Pass
