### ISSUE TITLE
Holiday scheme -> Calculating working days place holder

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#67]
Placeholder showing the wrong name

![Screenshot (201)](https://github.com/antonym8/Tentacle/assets/142376069/61d20842-862f-4a61-b059-65e0874d7977)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 04-04-2024

**Comment by Gokilavani-m8** [comment]
Not fixed

**Comment by M8Balaji** [comment]
Fixed

**Comment by Nounitha-m8** [comment]
Placeholder showing the wrong name

<img width="921" alt="Capture13" src="https://github.com/antonym8/Tentacle/assets/167423207/bfe71f3d-abda-4379-aa6a-a39c113d4977">

**Comment by Nounitha-m8** [comment]
Pass
