### ISSUE TITLE
Holiday -> Description in edit

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#72]
![Screenshot (205)](https://github.com/antonym8/Tentacle/assets/142376069/731f1de7-3e7b-4f70-8ddf-c6fe76a5cb97)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 04-04-2024

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Pass
