### ISSUE TITLE
Holiday -> Religion in edit

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#73]
Selected religion when add holiday but in edit dropdown not showing the selected religion

![Screenshot (206)](https://github.com/antonym8/Tentacle/assets/142376069/40947344-4b26-40ba-ac0d-84b671099828)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 04-04-2024

**Comment by M8Balaji** [comment]
Fixed

**Comment by Nounitha-m8** [comment]
Pass
