### ISSUE TITLE
Allowance -> Error message when create

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#74]
![Screenshot (207)](https://github.com/antonym8/Tentacle/assets/142376069/73a28d70-6452-4e8a-a111-1cab99799111)

**Comment by M8Balaji** [comment]
Fixed

**Comment by Nounitha-m8** [comment]
Edit - It is not working

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Edit - It is not working

**Comment by M8Balaji** [comment]
@Gokilavani-m8  Edit is working fine

**Comment by Nounitha-m8** [comment]
Pass
