### ISSUE TITLE
Deduction -> Empty toast message when create new deduction

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#75]
![Screenshot (208)](https://github.com/antonym8/Tentacle/assets/142376069/a693c225-7d4a-44c0-bb46-b160d88d8473)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 08-04-2024 (UI changed based on the client requirement)

**Comment by Gokilavani-m8** [comment]
Pass
