### ISSUE TITLE
Deduction -> Show -> Showing blank page

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#76]
![Screenshot (209)](https://github.com/antonym8/Tentacle/assets/142376069/4f112049-41ce-44fe-b45a-8b504bf35d43)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 08-04-2024 (UI changed. Based on client changes show page removed)

**Comment by Gokilavani-m8** [comment]
Pass
