### ISSUE TITLE
Client -> Salary calculation error message

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#77]
No validation message displayed when click save button without select the salary calculation

![Screenshot (210)](https://github.com/antonym8/Tentacle/assets/142376069/d1a55ea3-9c39-40d6-8be1-ea4674d1fa13)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed 08-04-2024

**Comment by Gokilavani-m8** [comment]
Not fixed

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Pass

**Comment by Gokilavani-m8** [comment]
1. Add>Toast Message - After adding a new client and clicking on the submit icon, a toast message should appear as Client Added Successfully. 
2. Edit>Toast Message - After editing a new client and clicking on the save icon, a toast message should appear as Client Updated Successfully. 
3. Mobile Number - It shouldn't accept 12 numbers

![Screenshot (94)](https://github.com/antonym8/Tentacle/assets/167422482/4226f073-f787-43c0-bda5-1a2d903bdc80)

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Bug#1,2,3 - Pass
1. Client Name - It shouldn't accept numbers & special characters as input. It shouldn't accept only the spaces as inputs. Spaces between the words should be acceptable.
2. Contact Person Name - It shouldn't accept numbers & special characters as input. It shouldn't accept only the spaces as inputs. Spaces between the words should be acceptable.
3. Need to remove the highlighted portion in mobile number

![Screenshot (247)](https://github.com/antonym8/Tentacle/assets/167422482/c7a4414e-9b93-4854-b847-080755bf8cf8)

4. Rename the Popup message as **Confirm to Delete Client...?**

![Screenshot (248)](https://github.com/antonym8/Tentacle/assets/167422482/e706e6bd-6378-4a69-9574-d89f8dadd741)

**Comment by Gokilavani-m8** [comment]
Pass
