### ISSUE TITLE
Client -> Contact person name placeholder

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#78]
Placeholder showing the wrong name

![Screenshot (211)](https://github.com/antonym8/Tentacle/assets/142376069/a9526d5e-f1bf-4952-a61e-9224b6b6abc7)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed 08-04-2024

**Comment by Gokilavani-m8** [comment]
Not fixed

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Pass
