### ISSUE TITLE
Employee management / Add -> Contact no accepts string value

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#81]
![Screenshot (214)](https://github.com/antonym8/Tentacle/assets/142376069/412b632a-a599-4ab0-9bb9-e9c123b82d5c)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed 08-04-2024

**Comment by Gokilavani-m8** [comment]
Not fixed

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Employee management / Add -> Contact no accepts string value - Fixed
After entering the family details and clicking on add new button, the toast message has displayed but it doesn't added in the page

![Screenshot (238)](https://github.com/antonym8/Tentacle/assets/167422482/8906aa60-1c8b-4820-a01f-b80e0a8a09e6)

**Comment by Gokilavani-m8** [comment]
Pass
