### ISSUE TITLE
Employee management / Add -> Blood pressure -> Proper error message should display

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#82]
![Screenshot (215)](https://github.com/antonym8/Tentacle/assets/142376069/fa5b7fec-883e-4d76-98cc-031bbb790209)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed 08-04-2023

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Pass

**Comment by Gokilavani-m8** [comment]
While leaving the blood pressure as blank or without selecting the blood pressure, it should be highlighted with alert message. But it is not highlighted.

**Comment by Gokilavani-m8** [comment]
Pass
