### ISSUE TITLE
Employee management / Add -> Diabetes error message

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#83]
Proper error message should display and spelling mistake in error message diabetes.

![Screenshot (216)](https://github.com/antonym8/Tentacle/assets/142376069/f4379c8c-87a7-4fb7-928f-3760e26b34d2)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed 08-04-2024

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Pass
