### ISSUE TITLE
Employee management / Add -> Document error message

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#84]
Proper error message should display in file upload

![Screenshot (217)](https://github.com/antonym8/Tentacle/assets/142376069/be7da1d1-6d41-47e6-82e8-8d3c55b8cacf)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed 08-04-2024

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Pass
