### ISSUE TITLE
Loan -> Newly added loan not showing in the list

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#91]
![Screenshot (224)](https://github.com/antonym8/Tentacle/assets/142376069/d4156cea-8f06-4c36-8638-1031cb78443e)

**Comment by muthuraja-m8itsolutions** [comment]
Not an Issue - Administrator needs to Approve, After approval it will reflect to appropriate page.
Left Side Sidebar -> Approve -> Finance

**Comment by Gokilavani-m8** [comment]
Pass
