### ISSUE TITLE
Agent commission -> Validation message

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#93]
No validation message displayed when try to save with blank data

![Screenshot (226)](https://github.com/antonym8/Tentacle/assets/142376069/c6ae9017-d594-4eba-a46c-3aa61b1e2fc2)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed 09-04-2024

**Comment by Nounitha-m8** [comment]
Agent Type> Proper validation message should displayed

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Pass
