### ISSUE TITLE
Expenses -> Newly added expenses not showing in the list page

### ISSUE THREAD

**Issue by antonym8** [antonym8/Tentacle#98]
![Screenshot (232)](https://github.com/antonym8/Tentacle/assets/142376069/32318dd9-54e9-4eb9-9a7b-c3ce951c612e)

**Comment by muthuraja-m8itsolutions** [comment]
Not an issue. First we need to approve, Then it will reflected to appropriate page.

**Comment by M8Balaji** [comment]
Check above comments

**Comment by Gokilavani-m8** [comment]
1. Approve>Expense>Expense Logs - Failed to approve

![Screenshot (95)](https://github.com/antonym8/Tentacle/assets/167422482/9e5f5561-666c-40f4-8d01-54ac13d9f6b1)

2. Employee code, Employee name, Department, Designation, Payment type, Type - These fields shouldn't be empty.

**Comment by M8Balaji** [comment]
@yogiofficemail  Data were coming empty

https://tssapidemo.m8itsolutions.in/api/expenseApproval

**Comment by yogiofficemail** [comment]
approval and reject fixed

**Comment by yogiofficemail** [comment]
it is same as  #95 implement that solution here 

> @yogiofficemail Data were coming empty
> 
> https://tssapidemo.m8itsolutions.in/api/expenseApproval

**Comment by Gokilavani-m8** [comment]
While entering employee name as ganesh, it has been shown as ganesh father in the expense list page

![Screenshot (393)](https://github.com/antonym8/Tentacle/assets/167422482/bd3253c0-60e7-4ce3-8a42-94b18818d867)

**Comment by yogiofficemail** [comment]
@M8Balaji {
    "employee_name": "Rasel",
    "fathers_name": "father",
    "id": 26,
    "employee_id": 142,
    "finance_category_id": 154,
    "amount": "60000.00",
    "total_paid_amount": "300.00",
    "remarks": null,
    "status": 0,
    "created_by": null,
    "updated_by": null,
    "created_at": "2024-07-08T07:51:19.000000Z",
    "updated_at": "2024-07-08T07:51:42.000000Z",
    "EmployeeCode": "TSS0126",
    "voucher_no": "VOD-0224",
    "department_name": "Security",
    "designation_name": null,
    "finance_category_name": "bank",
    "created_by_name": null
} show only employee name

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Loan & Expense>Expense>Expense Details - The employee name is different in expense details. The employee name should be same in expense details & expense list. Need to change it.

![Screenshot (405)](https://github.com/antonym8/Tentacle/assets/167422482/81821fbd-df41-4297-aee0-b34613788a9c)

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Pass
